package model;
// Generated 2020�~11��11�� �W��9:38:03 by Hibernate Tools 5.4.21.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int studentId;
	private String name;
	private String address;

	public Student() {
	}

	public Student(int studentId, String name, String address) {
		this.studentId = studentId;
		this.name = name;
		this.address = address;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
